name: Convert Shadowrocket Rules to Surge Rules

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Download sr_top500_banlist.conf
      run: |
        curl -L https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_banlist.conf -o sr_top500_banlist.conf

    - name: Convert conf to json
      run: |
        python convert_conf_to_json.py sr_top500_banlist.conf sbrule.json
        rm sr_top500_banlist.conf
        
    - name: Check for changes in sbrule.json
      id: check_changes
      run: |
        if git diff --quiet HEAD -- sbrule.json; then
          echo "No changes in sbrule.json"
          echo "::set-output name=changed::0"
        else
          echo "Changes detected in sbrule.json"
          echo "::set-output name=changed::1"
        fi
        
    - name: Commit and push JSON file
      if: steps.check_changes.outputs.changed == '1'
      run: |
        git config --local user.email "ftkey@qq.com"
        git config --local user.name "ftkey"
        git add sbrule.json
        git commit -m "Update sbrule.json"
        git push

